version: '3'
services:
  web:
    build: .
    working_dir: /webapp/app/
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
    env_file:
      - seed.env
    volumes:
    - .:/webapp
  #runs tests
  tests:
    build: .
    working_dir: /webapp/app/
    command: python3 manage.py test
    env_file:
      - seed.env
    volumes:
    - .:/webapp
  #db service should only be used in development
  db:
    image: postgres
    ports:
    - "5432:5432"
    environment:
     - POSTGRES_USER=app_dev
     - POSTGRES_PASSWORD=thepassword
  rabbit:
    restart: always
    image: rabbitmq:3-management
    hostname: rabbit
    env_file:
     - seed.env
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app worker -Q default -l info
    env_file:
      - seed.env
    environment:
      - DEBUG=False
    volumes:
      - .:/backend
  periodic_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app worker -Q beat -l info
    env_file:
      - seed.env
    environment:
      - DEBUG=False
    volumes:
      - .:/backend
  beat:
   #you should never have more than one instance of beat running or else you will get duplicate jobs.
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app beat
    env_file:
      - seed.env
    environment:
      - DEBUG=False
    volumes:
      - .:/backend
